### ISSUE TITLE
Pokémon with form differences does not have relative wiki page

### ISSUE THREAD

**Issue by lens0021** [patarapolw/squirdle#4]
```
https://pokemon.fandom.com/wiki/{{_POKEMON_NAME[en]}}
```
Say, if the secret Pokémon is 'Enamorus Therian Forme', the above URL is not valid.

**Comment by patarapolw** [comment]
That is easily fixed with `.replace(/ [^ ]+ forme?$/i, '')`, but I don't know about your Korean URL.

BTW, JavaScript regex already have Unicode group support, like `/[\p{sc=Han}\p{sc=Katakana}\p{sc=Hiragana}]/u` will work, if I need it.

The line of code is here - https://github.com/patarapolw/squirdle/blob/9399ed566d32b4840748aab2d53621d74492067d/src/pages/Game.vue#L497

**Comment by lens0021** [comment]
`/ [^ ]+ (forme?|mode)$/i` for 'Darmanitan Standard Mode' etc.
Or, if the wikis agree, we could create redirects on the wikis and it looks simpler for me.

**Comment by lens0021** [comment]
I've found more examples:

- Regional forms
- Zamazenta Crowned Shield / Hero of Many Battles
- Dusk Mane/Wings Necrozma
- Urshifu Single/Rapid Strike Style
- Calyrex Ice/Shadow Rider
- Heat/Wash/Frost/Fan/Mow Rotom
- Black/White Kyurem

**Comment by patarapolw** [comment]
I don't know if there is a good way to test if URL exists, other than a real HTTP request for HEAD, or web scraping.

**Comment by lens0021** [comment]
MediaWiki, a software Fandom uses, has APIs so you can use those, I think. Example documents are [API:Query](https://www.mediawiki.org/wiki/API:Query) and [API:Info](https://www.mediawiki.org/wiki/API:Info#JavaScript). And example queries are:

- https://pokemon.fandom.com/api.php?action=query&titles=Pikachu
- https://pokemon.fandom.com/api.php?action=query&titles=Nonexisting_name

But I am afraid it is overdoing.

**Comment by patarapolw** [comment]
Apparently, a good web scraping is better than API. (Looking at href's in the scraped website).

I fixed the missing links in English's refs <https://github.com/patarapolw/squirdle/blob/main/translation/en-ref.json>, but you will have fix the Korean version yourself (I can't read Korean). <https://github.com/patarapolw/squirdle/blob/main/translation/ko-ref.json>

**Comment by lens0021** [comment]
For Korean, I will create redirects on the Korean Pokémon wiki later rather than making edits on this repository, as I think it is a sort of technical debt to make you have to review more and more foreign languages...

**Comment by lens0021** [comment]
> For Korean, I will create redirects on the Korean Pokémon wiki later rather than making edits on this repository, as I think it is a sort of technical debt to make you have to review more and more foreign languages...

[Done!](https://pokemon.fandom.com/ko/wiki/%ED%8A%B9%EC%88%98:%EA%B8%B0%EC%97%AC?limit=50&contribs=user&target=Leslie1289&namespace=&tagfilter=&newOnly=1&start=2022-03-03&end=2022-03-05) Thank you.
